/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './message.component.ngfactory';
import * as i2 from './message.component';
import * as i3 from './message.service';
import * as i4 from '@angular/common';
import * as i5 from './message-list.component';
const styles_MessageListComponent:any[] = ([] as any[]);
export const RenderType_MessageListComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_MessageListComponent,data:{}});
function View_MessageListComponent_1(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'app-message',
      ([] as any[]),(null as any),(null as any),(null as any),i1.View_MessageComponent_0,
      i1.RenderType_MessageComponent)),i0.ɵdid(49152,(null as any),0,i2.MessageComponent,
      [i3.MessageService],{message:[0,'message']},(null as any))],(_ck,_v) => {
    const currVal_0:any = _v.context.$implicit;
    _ck(_v,1,0,currVal_0);
  },(null as any));
}
export function View_MessageListComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n      '])),(_l()(),i0.ɵeld(0,
      (null as any),(null as any),4,'div',[['class','col-md-8 col-md-offset-2']],(null as any),
      (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
      ['\n          '])),(_l()(),i0.ɵand(16777216,(null as any),(null as any),1,(null as any),
      View_MessageListComponent_1)),i0.ɵdid(802816,(null as any),0,i4.NgForOf,[i0.ViewContainerRef,
      i0.TemplateRef,i0.IterableDiffers],{ngForOf:[0,'ngForOf']},(null as any)),(_l()(),
      i0.ɵted((null as any),['\n      '])),(_l()(),i0.ɵted((null as any),['\n  ']))],
      (_ck,_v) => {
        var _co:i5.MessageListComponent = _v.component;
        const currVal_0:any = _co.messages;
        _ck(_v,4,0,currVal_0);
      },(null as any));
}
export function View_MessageListComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'app-message-list',
      ([] as any[]),(null as any),(null as any),(null as any),View_MessageListComponent_0,
      RenderType_MessageListComponent)),i0.ɵdid(114688,(null as any),0,i5.MessageListComponent,
      [i3.MessageService],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const MessageListComponentNgFactory:i0.ComponentFactory<i5.MessageListComponent> = i0.ɵccf('app-message-list',
    i5.MessageListComponent,View_MessageListComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvc29lcmUvRG9jdW1lbnRzL1dlYnN0b3JtL1NvdXJjZVRyZWUvMDIvYXNzZXRzL2FwcC9tZXNzYWdlcy9tZXNzYWdlLWxpc3QuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL3NvZXJlL0RvY3VtZW50cy9XZWJzdG9ybS9Tb3VyY2VUcmVlLzAyL2Fzc2V0cy9hcHAvbWVzc2FnZXMvbWVzc2FnZS1saXN0LmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L1VzZXJzL3NvZXJlL0RvY3VtZW50cy9XZWJzdG9ybS9Tb3VyY2VUcmVlLzAyL2Fzc2V0cy9hcHAvbWVzc2FnZXMvbWVzc2FnZS1saXN0LmNvbXBvbmVudC50cy5NZXNzYWdlTGlzdENvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvc29lcmUvRG9jdW1lbnRzL1dlYnN0b3JtL1NvdXJjZVRyZWUvMDIvYXNzZXRzL2FwcC9tZXNzYWdlcy9tZXNzYWdlLWxpc3QuY29tcG9uZW50LnRzLk1lc3NhZ2VMaXN0Q29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG4gICAgICA8ZGl2IGNsYXNzPVwiY29sLW1kLTggY29sLW1kLW9mZnNldC0yXCI+XG4gICAgICAgICAgPGFwcC1tZXNzYWdlXG4gICAgICAgICAgICAgICAgICBbbWVzc2FnZV09XCJtZXNzYWdlXCJcbiAgICAgICAgICAgICAgICAgICpuZ0Zvcj1cImxldCBtZXNzYWdlIG9mIG1lc3NhZ2VzXCI+PC9hcHAtbWVzc2FnZT5cbiAgICAgIDwvZGl2PlxuICAiLCI8YXBwLW1lc3NhZ2UtbGlzdD48L2FwcC1tZXNzYWdlLWxpc3Q+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0VVO01BQUE7b0NBQUEsVUFBQTtNQUFBO0lBQ1E7SUFEUixXQUNRLFNBRFI7Ozs7b0JBRlYsNkNBQ007TUFBQTtNQUFBLDBEQUFzQztNQUFBLG1CQUNsQztNQUFBLHFDQUFBO3VDQUFBLHlDQUV1RDthQUFBLDhCQUNyRDs7O1FBRE07UUFGUixXQUVRLFNBRlI7Ozs7b0JDRlY7TUFBQTtxQ0FBQSxVQUFBO01BQUE7SUFBQTs7OzsifQ==
